### ISSUE TITLE
API 형식으로 만들어주심시오.

### ISSUE THREAD

**Issue by nnnlog** [organization/ParticleChase-PMMP#1]
ParticleChaseMain::getInstance()->
로 setParticle(), removeParticle(), getParticle() 와 같은 메서드를 통하여 외부 플러그인에서 접근 가능하게 해주심시오..

**Comment by PresentKim** [comment]
에...알겟슴미다

**Comment by PresentKim** [comment]
# **암을 발생시키는 질문들**  
  
### **💢이 오류가 나는데, 어떻게 해야돼요?**  
> 저는 오류만 보고서 소스까지 알아낼 수 없습니다  
> 저는 오류만 보고서 소스까지 알아내서 해결해드릴 의무가 없습니다  
  
### **💢이 소스 안되는데, 어떻게 해야돼요?**  
> 저는 소스만 보고서 어떤 오류가 날지 알아낼 수 없습니다  
> 저는 소스만 보고서 어떤 오류가 날지 알아내서 해결해드릴 의무가 없습니다  
  
### **💢이건 소스고 이건 오류인데, 어떻게 해야돼요?**  
> 저는 잘못된 소스를 보고서 해당 프로그램의 본 목적을 알아낼 수 없습니다  
> 저는 잘못된 소스를 보고서 해당 프로그램의 본 목적을 알아내서 해결해드릴 의무가 없습니다  
  
### **💢이게 소스인데, 이거 맞아요?**  
> 저는 당신의 유효성 검사기가 아닙니다
> 직접 실행하여 바로 얻을 수 있는 해답을 인간에게서 얻으려 하지 마세요
  
-------  
  
### **💩PHP를 배우지 않고 질문하는 경우**  
> 영어를 배우지 않고 영문 도서를 출판하려고 하지 마세요  
> 언어를 사용하기 위해서는 당연히 언어를 배워야합니다
  
### **💩PMMP소스를 읽지 않고 질문하는 경우**  
> 컴퓨터에 대해 알아보지도 않고 주변 기기를 발명하려고 하지 마세요  
> API 자체가 아닌 API를 이용한 사례들만 참고하는건 당신이 멍청하다고 홍보하는 것과 같습니다
  
### **💩타인의 소스를 수정하면서 질문하는 경우**  
> 프로그램의 오류는 제작자에게 문의하세요  
> 프로그램의 오류는 제작자의 책임이지 당신과 저의 책임이 아닙니다

**Comment by PresentKim** [comment]
이제 귀찮슴미다 ㅎㅎ

**Comment by nnnlog** [comment]
ㅇ

**Comment by LeinneSW** [comment]
아 ㅋㅋ
